export const errorCodeLUT: Record<string, string> = {
  maximum: "FormatViolation",
  minimum: "FormatViolation",
  maxLength: "FormatViolation",
  minLength: "FormatViolation",
  exclusiveMaximum: "OccurenceConstraintViolation",
  exclusiveMinimum: "OccurenceConstraintViolation",
  multipleOf: "OccurenceConstraintViolation",
  maxItems: "OccurenceConstraintViolation",
  minItems: "OccurenceConstraintViolation",
  maxProperties: "OccurenceConstraintViolation",
  minProperties: "OccurenceConstraintViolation",
  additionalItems: "OccurenceConstraintViolation",
  required: "OccurenceConstraintViolation",
  pattern: "PropertyConstraintViolation",
  propertyNames: "PropertyConstraintViolation",
  additionalProperties: "PropertyConstraintViolation",
  type: "TypeConstraintViolation",
};
